### PR TITLE
Use librsvg 0.6.0 w/ node v4 support

### PR DESCRIPTION
**Pull request by heilage-nsk**
Version update:
- https://github.com/2gis/node-rsvg
- https://www.npmjs.com/package/librsvg

### CODE REVIEW

**Comment by ben-eb** [comment]
Thanks! :+1:

**Comment by ben-eb** [comment]
@heilage-nsk Any ideas why this build is failing on v4? https://travis-ci.org/ben-eb/gulp-rsvg/jobs/82137046

**Comment by heilage-nsk** [comment]
@ben-eb 
I've updated .travis.yml and moved 0.6.0 release tag, should be fine now :)

**Comment by heilage-nsk** [comment]
Agh. It doesn't work this way. Just a minute, I'll make a 0.6.1

**Comment by heilage-nsk** [comment]
@ben-eb done! Update dependency version to 0.6.1 please.
I'm not sure about npm caches ttl, but it seems to be available already.

**Comment by ben-eb** [comment]
@heilage-nsk Done, but throwing the same errors. Should I use the same configuration as your travis.yml?

https://travis-ci.org/ben-eb/gulp-rsvg/jobs/82143596

**Comment by heilage-nsk** [comment]
Seems like it doesn't look into dependencies' travis.yml. librsvg's build is fine: https://travis-ci.org/2gis/node-rsvg
Yes, probably you should copy env and addons sections to your travis.yml.

**Comment by ben-eb** [comment]
@heilage-nsk It passes! Thanks for your support and contribution. :+1:

**Comment by heilage-nsk** [comment]
Thank you too :) :+1:

**Pull request merged**
